
# Spring Cloud Gateway配置
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:XdiwWEW15e}
      database: ${REDIS_DATABASE:0}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0
  security:
    jwt:
      blacklist:
        # 黑名单键前缀
        prefix: "jwt:blacklist:"
        # 是否跳过 client_credentials（机器到机器）令牌的黑名单校验
        skip-client-credentials: true
        # 按路径前缀跳过（逗号分隔），例如内部健康检查、内部回调
        skip-path-prefixes: /actuator/,/internal/
    oauth2:
      resourceserver:
              jwt:
                issuer-uri: http://service-auth:30003  # Authorization Server 地址（使用服务名，适用于微服务环境）
                # 或显式配置 JWK Set URI
                # jwk-set-uri: http://service-auth:30003/oauth2/jwks
  # OAuth2 Resource Server 配置


  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

      # 路由配置
          routes:
            - id: 认证服务
              uri: lb://service-auth
              predicates:
                - Path=/api/user/**,/oauth2/**
              filters:
                - name: UserInfoGatewayFilter  # 应用用户信息过滤器
            - id: 系统服务
              uri: lb://service-demo
              predicates:
                - Path=/demo/**
              filters:
                - StripPrefix=1
                - name: UserInfoGatewayFilter  # 应用用户信息过滤器
            # 示例：其他服务路由也可以应用用户信息过滤器
            # - id: service-system
            #   uri: lb://service-system
            #   predicates:
            #     - Path=/system/**
            #   filters:
            #     - StripPrefix=1
            #     - name: UserInfoGatewayFilter




knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : OpenAPI3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - gateway

# 链路追踪配置
management:
  zipkin:
    tracing:
      endpoint: http://117.50.197.170:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1