metadata:
- appName: ''
  dataId: service-demo.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: service-feishu.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: gateway.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: service-system.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: service-wechatwork.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: service-auth.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
